### ISSUE TITLE
no output / popup ?

### ISSUE THREAD

**Issue by j1gg3** [bdetweiler/entrust-grid-challenge-automation#1]
Hi,

unfortunately I'm not getting any popup as of the script is being launched. 
I also just tried to enter some text in a simple text editor, with the same result.

Did I miss something?

**Comment by bdetweiler** [comment]
Hrm, you must have missed something. This is for a very specific use case in which the web page presents the user with a text code that corresponds to a unique grid decoder, and then enters the answer into a text field. You may be able to use some of this code for your proposes, but that's all this does out of the box.

**Comment by j1gg3** [comment]
Thanks for your reply. Indeed I have exactly the same scenario you described. I am logging every day into a secured environment where I have to enter a grid challenge response code which has 5 rows and fields from A to J. I just google how to automate this annoying input and found your site. 

As of your script starts I can only see that the site's text also with the containing fields has been copied into the clipboard e.g. Enter a response to the grid challenge [D1] [I4] [J4] . 

And thats it so far :(

**Comment by bdetweiler** [comment]
Ok, great. I wrote this a long time ago, but I believe you have to place the cursor in the input box when you run the script. Obviously you'll need to change the code to match your own grid card, and it looks like you have a 3-digit code, and mine was looking for a 4-digit code, so you'll need to update that.

**Comment by j1gg3** [comment]
Thanks man, it is working now :-)
